[build]
  # Base directory for the build
  base = "client"
  
  # Build command - clean install to fix rollup issue
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"
  
  # Directory to publish
  publish = "dist"

# Redirect all routes to index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
